import { useEffect, useMemo, useState } from "react"

// Generated by https://quicktype.io

export interface Tamu {
	NamaLengkap: string;
	JumlahHadir: string;
	Kehadiran:   string;
	id:          number;
}


const useFetchData = <Pay, >(url: string): {data: Pay | null; isDone: boolean} => {
	const [data, setData] = useState<Pay | null>(null)
	const [isDone, setIsDone] = useState(false)

	useEffect(() => {
		fetch(url)
		 .then((res) => res.json())
		 .then((d: Pay) => {
			setData(d);
			setIsDone(true)
		 })
	}, [url])

	return{
		data,
		isDone,
	};
}

const CustomHookComponent = () => {
	const { data, isDone } = useFetchData<Tamu[]>("/data.json");
	const Kehadiran = useMemo(
		() => (data || []).filter((tamu) => tamu.Kehadiran.includes("tidak hadir")), [data]
	)

	return (
		<>
			<div>
				<h1>Tamu pertama</h1>
				{isDone && (
					<h3>{data![0].NamaLengkap}</h3>
				)}
			</div>
			<div>
				<h1>Tamu tidak hadir</h1>
				{Kehadiran.length && (
					<h3>{Kehadiran![0].NamaLengkap}</h3>
				)}
			</div>
		</>
	)
}

export default CustomHookComponent